steps:
# build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'DockerFile' ,'-t', 'gcr.io/${PROJECT_ID}/weather-app', '.']

# push docker image to the repository
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/weather-app']

# patch kubernetes deployment to trigger rolling update
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'patch', 'deployment', '{_ENV}-weather-app', '-n', 'default', '-p',
          '{"spec":{"strategy": {"rollingUpdate": {"maxSurge": 1,"maxUnavailable": 1},"type": "RollingUpdate"},
          "template":{"spec":{"containers":[{"name":"{_ENV}_weather-app","image":"gcr.io/${PROJECT_ID}/weather-app"}]}}}}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod-cluster'
timeout: 1200s
